# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Remove blank line between shell prompts
add_newline = false

# Format for showed
# $git_status
format = """
$directory$conda$git_branch$git_state$git_metrics
$username: """

[character]
success_symbol = "[](bold #a7c080)"
error_symbol = "[](bold #e67e80)"

[conda]
symbol = " "
format = "\\([$symbol$environment](bold #a7c080)\\) "
[directory]
truncation_length = 3
truncation_symbol = ""
style = "#a7c080"
repo_root_style = "bold #7fbbb3"

[git_commit]
only_detached = false

[git_branch]
style = "bold #7fbbb3"

[git_metrics]
disabled = false
only_nonzero_diffs = false
added_style = "#a7c080"
deleted_style = "#e67e80"
format = '<([+$added]($added_style);([-$deleted]($deleted_style)))>'

[git_status]
conflicted = "🏳"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
up_to_date = "✓"
stashed = "📦"
modified = "M"
staged = '[\($count\)](bold #a7c080)'
renamed = "👅"
deleted = "🗑"
style = "bold #7fbbb3"

[username]
show_always = true
format = "[$user]($style)"
style_user = "bold #a7c080"
