-- vim.keymap.set("n", "<C-n>", ":Neotree toggle <cr>", { silent = true })
-- vim.keymap.set("n", "<leader>n", ":Neotree dir=%:p:h<cr>")
--
-- require("neo-tree").setup({
-- 	window = {
-- 		mappings = {
-- 			["P"] = {
-- 				"toggle_preview",
-- 				config = {
-- 					use_float = true,
-- 				},
-- 			},
-- 		},
-- 	},
-- })
