[window]
padding = { x = 1, y = 2 }


[font]
normal = { family="AnonymousPro", style="Regular" }
bold = { family="AnonymousPro", style="Bold" }
italic = { family="AnonymousPro", style="Italic" }
bold_italic = { family="AnonymousPro", style="Bold" }
size = 16

[cursor]
style = {shape="Block", blinking="On"}
vi_mode_style = {shape="Beam", blinking="On"}

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/bamboo.toml",
]
