[colors.bright]
black = "#000000"
blue = "#7788AA"
cyan = "#708090"
green = "#789978"
magenta = "#ffaa88"
red = "#ffaa88"
white = "#deeeed"
yellow = "#abab77"

[colors.normal]
black = "#000000"
blue = "#7788AA"
cyan = "#708090"
green = "#789978"
magenta = "#ffaa88"
red = "#ffaa88"
white = "#deeeed"
yellow = "#abab77"

[colors.primary]
background = "#101010"
foreground = "#cccccc"

[colors.selection]
background = "#cccccc"
foreground = "#101010"
